gcp_project_id = "labgce-424207"
gcp_service_account_key_file_path = "../credentials/labgce-service-account-key.json"
gce_instance_name = "gce-srv-0"
gce_instance_user = "gce-adm"
gce_ssh_pub_key_file_path = "../credentials/labgce-ssh-key.pub"